version: '3.5'

services:
  front:
    build: .
    networks:
      - mehrancms
    ports:
      - '${EXPOSED_PORT}:3000'

  networks:
    mehrancms:
      external: true
      name: mehranCMS-networks
