# This is a basic workflow to help you get started with Actions

name: Deployment Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #       - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: SSH sever connection
        #         uses: appleboy/ssh-action@master

        #         with:
        #           host: ${{ secrets.HOST }}
        #           username: ${{ secrets.USERNAME }}
        #           key: ${{ secrets.OMG_SECRET }}
        #           port: ${{ secrets.PORT }}
        #           script: |
        #             cd my-blog-cms
        #             git fetch
        #             git checkout origin/main
        #             docker-compose up --build -d
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd portfolio-website
            git fetch origin main
            git reset --hard origin/main
            docker-compose up --build -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #           passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.OMG_SECRET}}
